### ISSUE TITLE
Delete This

### ISSUE THREAD

**Issue by baolongv3** [kush412/AnIsNotSus#1]
Delete this
![c3c](https://user-images.githubusercontent.com/43814741/167077458-95b65bc7-f015-4375-9fa0-2c8e929dd1e3.jpg)

**Comment by kush412** [comment]
> Delete this ![c3c](https://user-images.githubusercontent.com/43814741/167077458-95b65bc7-f015-4375-9fa0-2c8e929dd1e3.jpg)

no
